version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  main_app:
    build: ./main_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: main_app_db
      NOTIFICATION_SERVICE_URL: http://notification_service:3000/notifications
      SCRAPING_SERVICE_URL: http://scraping_service:3000/scrape
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./main_app:/app
    networks:
      - app-network

  auth_service:
    build: ./auth_service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: auth_service_db
    depends_on:
      - db
    ports:
      - '3001:3000'
    volumes:
      - ./auth_service:/app
    networks:
      - app-network

  notification_service:
    build: ./notification_service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: notification_service_db
    depends_on:
      - db
    ports:
      - '3002:3000'
    volumes:
      - ./notification_service:/app
    networks:
      - app-network

  scraping_service:
    build: ./scraping_service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: scraping_service_db
    depends_on:
      - db
    ports:
      - '3003:3000'
    volumes:
      - ./scraping_service:/app
    networks:
      - app-network

  sidekiq:
    build: ./main_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: main_app_db
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - ./main_app:/app
    networks:
      - app-network

  redis:
    image: redis:6.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
