default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: main_app_test

production:
  <<: *default
  database: main_app_production
  username: main_app
  password: <%= ENV['MAIN_APP_DATABASE_PASSWORD'] %>
